name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16", "17"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
          scope: "@hpcc-js"
      - run: npm ci
      - run: npm run install-deps
      - run: npm run lint
      - run: npm run build-docs
      - run: npm run build
      - run: npm run test
